"""add_retry_fields_and_sms_retries_table

Revision ID: d4529b4d8920
Revises: f48e6a095cfb
Create Date: 2025-10-09 13:51:28.297247+00:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd4529b4d8920'
down_revision = 'f48e6a095cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_retries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sms_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sms_requests', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('sms_requests', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('sms_requests', sa.Column('failed_providers', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.add_column('sms_requests', sa.Column('is_permanently_failed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_requests', 'is_permanently_failed')
    op.drop_column('sms_requests', 'failed_providers')
    op.drop_column('sms_requests', 'max_retries')
    op.drop_column('sms_requests', 'retry_count')
    op.drop_table('sms_retries')
    # ### end Alembic commands ###